server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG

spring:
  application:
    name: campinglog-back-server
  #  datasource:
  #    driver-class-name: org.mariadb.jdbc.Driver
  #    url: jdbc:mariadb://localhost:3306/mydb?characterEncoding=UTF-8
  #    username: mydbid
  #    password: mydbpw
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: ${H2_DB_USERNAME}
    password: ${H2_DB_PASSWORD}
  #  sql:
  #    init:
  #      mode: never
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
#    properties:
#      hibernate:
#        format_sql: true

jwt:
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION}
  header-string: Authorization
  token-prefix: "Bearer "
