server:
  port: 8080

spring:
  application:
    name: campinglog-back-server
  #  datasource:
  #    driver-class-name: org.mariadb.jdbc.Driver
  #    url: jdbc:mariadb://localhost:3306/mydb?characterEncoding=UTF-8
  #    username: mydbid
  #    password: mydbpw
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: ${H2_DB_USERNAME}
    password: ${H2_DB_PASSWORD}
  #  sql:
  #    init:
  #      mode: never
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${K_CLIENT_ID}
            client-secret: ${K_CLIENT_SECRET}
            client-name: Kakao
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION}
  header-string: Authorization
  token-prefix: "Bearer "

refresh:
  secret_key: ${REFRESH_SECRET_KEY}
  expiration: ${REFRESH_EXPRIATION}
  cookie: "s_rt"

external:
  camp:
    base-url: ${BASE_URL}
    api-key: ${CAMP_KEY}

management:
  endpoints:
    web:
      exposure:
        include: "*"